spring:
  application:
    name: museum

  datasource:
    url: jdbc:h2:mem:museum;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false

  config:
    import: classpath:version-info.yml

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration


server:
  port: 8080

logging:
  level:
    org.flywaydb: INFO


