openapi: 3.0.0
info:
  title: Hello World API
  version: 1.0.0
paths:
  /:
    get:
      summary: Возвращает приветствие
      operationId: getHello
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
          example: Hello, world!
